### ISSUE TITLE
Gitlab pipeline broken

### ISSUE THREAD

**Issue by Nice3point** [jeremytammik/RevitLookup#103]
As @peterhirn wrote https://github.com/jeremytammik/RevitLookup/pull/101#issuecomment-953554852, we need to decide whether to fix the build on gitlab or remove it altogether, leaving only github.

**Comment by jeremytammik** [comment]
shall we close this now? are you guys happy with the new state of things?

**Comment by Nice3point** [comment]
> PR coming soon.

@peterhirn Did you want to make any other changes to the project? Readme updated

**Comment by peterhirn** [comment]
Nice, thank you. Issue can be closed.

I will add a archived notice to lookupbuilds.com with a link to https://github.com/jeremytammik/RevitLookup#installation

**Comment by jeremytammik** [comment]
thank you both for documenting, checking and confirming. 

ever so many thanks once again to @peterhirn for setting up lookupbuilds.com back in 2017 and maintaining it so diligently ever since: 

https://thebuildingcoder.typepad.com/blog/2017/04/forgefader-ui-lookup-builds-purge-and-room-instances.html#3

very many thanks to @Nice3point for implementing the new streamlined system!
