### ISSUE TITLE
CylindricalFace has no Radius property in snoop summary

### ISSUE THREAD

**Issue by yuryleb2** [jeremytammik/RevitLookup#264]
Snoop summary shows Axis and Origin properties of CylindricalFace but no Radius one:
![image](https://github.com/jeremytammik/RevitLookup/assets/155540915/be1f45d7-3a6a-4aee-9f35-07238c9588bf)
This property is public similar to Axis and Origin:
![image](https://github.com/jeremytammik/RevitLookup/assets/155540915/80295f99-7954-42e4-8c5c-3b3c1546b8ab)

Steps to reproduce:
- Open some of standard Revit sample files, say Snowdon Towers Sample Plumbing.rvt
- It's better to open some 3D view, say '3D Wander' in this file
- Select a cylindrical element, say a pipe or duct. It could be Cast Iron pipe 1689158 from this file
- Snoop this element in RevitLookup, select 'Geometry (Options)', then a 'Solid' from IEnumerable list of opened Active view geometry, then select 'Faces' to see groupped cylindrical faces and their properties - there will be Axis and Origin at the bottom but no Radius one

**Comment by Nice3point** [comment]
Radius requires an index entry, so it is not displayed because it was not supported up to that moment
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/db19d767-a008-4acf-b0b2-b30c9cbb2c05)

If you want to see all properties, enable this option
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/c8ac59e7-e2a9-4329-841a-3053babb1a15)

We will add radius support in future updates, thanks for report

**Comment by Nice3point** [comment]
Added in the 2025.0.9 update
