### ISSUE TITLE
Continuous Integration no longer working

### ISSUE THREAD

**Issue by WspDev** [jeremytammik/RevitLookup#59]
Latest build is 2020.0.0.3: [https://lookupbuilds.com/index.html?prefix=releases/](url)

**Comment by jeremytammik** [comment]
Oh dear. Thank you for letting me know. I passed on the message to buildinformed and Peter Hirn and hope he will be able to take a look in a timely fashion. Cheers.

**Comment by jeremytammik** [comment]
Submitted this as an issue on lookupbuilds.com as well: https://github.com/buildinformed/lookupbuilds-com/issues/1

**Comment by peterhirn** [comment]
Hello,

starting last Sunday multiple CI-breaking changes were introduced:
- upgrade to net48 (already fixed in CI)
- breaking changes to solution file, see https://github.com/jeremytammik/RevitLookup/commit/67395aa081319399ae44dbd84534d5c04be6e46b

Updating the CI config for the new solution structure will take a little time.

In the meantime users should be able to use the checked-in installer, which I assume is installing for Revit 2021 (?) https://github.com/jeremytammik/RevitLookup/blob/master/installer/Revit%20Lookup-SetupFiles/Revit%20Lookup.msi

**Comment by jeremytammik** [comment]
@peterhirn @harrymattison @WspDev does anyone have an idea how this can be fixed? do we need to revert back to the previous state and remove the multi-version support? can the multi-version support be adapted so that the CI is not affected? i am no expert in either of these two area!

**Comment by harrymattison** [comment]
I don't know how lookupbuilds works, but I am happy to help fix this if there is a change to the solution that would resolve it

**Comment by peterhirn** [comment]
## CI
I fixed the config. For now the CI will only build the addin for Revit 2021, older versions are still available.

Since the CI is disconnected from this repository, it is easy to break it accidentally. A better approach would be to integrate the CI builds here, using a hosted CI like GitHub Actions, Gitlab CI, Travis CI, AppVeyor, etc. They are all building the project based on a checked-in file (eg. `.gitlab-ci.yml`, `ci.yml `, etc.). Therefore contributors to this project can adapt the build config based on their changes and are directly responsible if the CI breaks.

Before moving to a hosted CI some questions should be considered:
- Who has access to the backend of the CI?
- Which certificate should be used for signing the assembly?
- The build needs access to proprietary Autodesk assemblies, eg. `RevitAPI.dll`. Since there is no NuGet package containing these assemblies, they need to be uploaded to the CI and made available during build.

Since (CI-)breaking changes to this repository are very rare, it's no problem for us to keep fixing the config. Worst case is this issue, where we didn't produce a valid build for a week.

## Multi-version support
You don't need to build against the exact version of the Revit API you want to support, unless there is a breaking change to the subset of the API the project is using.

For example, we build most of our addins against Revit 2019 API (or older) but support 2019, 2020 and 2021. All with a single assembly/dll.

I propose the following changes to Lookup:
- Set framework to net472
- Depend only on Revit 2019 assemblies: `RevitAPI.dll`, `RevitAPIUI.dll`
- Remove unused assembly references: `AdWindows`, `RevitAPIIFC`, `RevitAPIMacros`, `RevitAPIUI`, `RevitAPIUIMacros`
- Revert solution configuration back to Release/Debug

This will produce a single assembly which can be loaded in 2019, 2020 and 2021. 

Eventually there will be a breaking change to the subset of the API Lookup is using. Then you can decide if you want to drop support for older versions or build multiple assemblies.

## Autodesk App Store
We published a bunch of addins to the App Store lately. I've been thinking, @jeremytammik would you be open to the idea that we release Revit Lookup as free app in the App Store under our account? Of course with full disclosure that this is a open source app and links to this repository.

**Comment by jeremytammik** [comment]
@peterhirn I agree with your analysis and suggestions for the simplest possible solution. I also believe that the possibility to download RevitLookup from the AppStore would be much appreciated my many developers, and especially by many non-developer users interested in digging a little bit deeper into the database. I suggest we proceed as you suggest. Thank you very much!

**Comment by harrymattison** [comment]
I am working on some big improvements to Revit Lookup. I was planning to
submit them to the open-source repo, but if it is going on the App Store
I'd also like the email addresses of the people who download it. I could
submit it as a separate app, but it that the best solution?

**Comment by mattmas** [comment]
> 
> For example, we build most of our addins against Revit 2019 API (or older) but support 2019, 2020 and 2021. All with a single assembly/dll.
@peterhirn - while I agree you can get away with this most of the time, this feels like a case where it is less likely to work/be appropriate, even with the newer reflection-based approach. We’ve addressed this before with conditional builds, producing one DLL per version, but put into a single package.
I haven’t looked at the current implementation of the units code in RevitLookup, but that’s a substantial change in 2021.

I think getting it onto the AppStore would be a big win for power users everywhere.

-Matt

**Comment by peterhirn** [comment]
I think contacting users who downloaded this free open-source app, or any further processing of their contact information for that matter, would be unacceptable.

> @peterhirn - while I agree you can get away with this most of the time, this feels like a case where it is less likely to work/be appropriate, even with the newer reflection-based approach. We’ve addressed this before with conditional builds, producing one DLL per version, but put into a single package.
I haven’t looked at the current implementation of the units code in RevitLookup, but that’s a substantial change in 2021.

(not sure who commented this) All 2020 and 2021 assemblies on https://lookupbuilds.com have been build against Revit 2019 (I never updated `RevitAPI.dll`). Please let me know if this causes problems.

**Comment by harrymattison** [comment]
Peter - That's how the App Store works.

https://apps.autodesk.com/en/public/termsofuse
https://www.autodesk.com/company/legal-notices-trademarks/privacy-statement


How Does Autodesk Disclose Your Personal Data?

We disclose the categories of information described above to the following
categories of persons:

Our business partners, such as integration partners, channel partners
(e.g., resellers) and Autodesk’s App Store publishers, with whom you
interact to facilitate your relationship with Autodesk and those business
partners for any of the purposes described in our or those business
partners’ privacy statements

**Comment by peterhirn** [comment]
For everyone who is not in the loop, the Autodesk App Store will disclose personal information of the user to the publisher, at least:

- Store
- E-mail
- Full Name
- Job Title
- Company Name
- Country

Again, I think **any further processing** of the contact information by the publisher would be unacceptable in this case, as we are only repackaging an open-source tool. This will be hard to prove/guarantee.

@harrymattison I understand you don't want your contributions to Lookup to be published under our corporate account or would rather publish the app under your corporate account. Let's reconsider our options. I think we can find a way which still yields the desired outcome (Lookup in App Store) but is not biased towards a specific company.

**Comment by jeremytammik** [comment]
Hi everybody, how can we move forward with this, please? @harrymattison , I would very much appreciate seeing the enhancements that you mention. @peterhirn , i do not think a version based on Revit 2019 API will work, because we may very well need to add some support for the new unit types or other more recent features at some point. I don't care much about the multi-version support. I like the CI support. I can imagine that customers will very much appreciate having RevitLookup available in the AppStore. Now what?

**Comment by peterhirn** [comment]
Hey Jeremy,

if multi-version support is not required I think this project should only depend on the latest Revit assemblies. Older versions will still be available for download from lookupbuilds anyways.

Regarding the App Store: after this conversation I'm convinced this project should not be released by a for-profit corporation, which could eventually abuse personal information of users. Would it be possible that you - or someone you trust - create a "Community" publisher in the App Store? We could support you by providing all necessary images, descriptions, F1-button support and other things Autodesk reviewers require when submitting an app.

**Comment by jeremytammik** [comment]
hi peter, that sounds like a great idea. yes, absolutely, i will ask the appstore people whether they can support with with that.l thank you for the great suggestion!

**Comment by jeremytammik** [comment]
@harrymattison @peterhirn : I discussed this with the AppStore guys, and they told me now (for the second time):

As mentioned earlier in my email, they can submit the app through app submission process:

https://damassets.autodesk.net/content/dam/autodesk/www/adn/pdf/desktop-app-submission-process-overview.pdf
 
We will be happy to assist the publisher if they have any questions regarding submission.

I asked about creating a special publisher for the community and received no answer or comment on that.

If anyone is willing to go ahead with the publication with the guarantee that the customer data will not be processed in any way whatsoever, I would be happy to proceed as we are now.

What do you think? Am I being too naive?

**Comment by jeremytammik** [comment]
Fixed by pull request #61
