### ISSUE TITLE
Unhandled exception on View.GetTemplateParameterIds

### ISSUE THREAD

**Issue by RevitArkitek** [jeremytammik/RevitLookup#65]
In a view (whether its a view template or not), I click on GetTemplateParameterIds, following error is thrown:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RevitLookup.Snoop.Data.SnoopableObjectWrapper.GetUnderlyingType()
   at RevitLookup.Snoop.Forms.Objects.AddObjectsToTree(IEnumerable`1 snoopableObjects)
   at RevitLookup.Snoop.Forms.Objects.CommonInit(IEnumerable`1 objs)
   at RevitLookup.Snoop.Forms.Objects..ctor(ArrayList objs)
   at RevitLookup.Snoop.Data.Enumerable.DrillDown()
   at RevitLookup.Snoop.Utils.DataItemSelected(ListView lvCur)
   at RevitLookup.Snoop.Forms.Objects.DataItemSelected(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jeremytammik** [comment]
Thank you for pointing it out. Are you a programmer? Do you have Visual Studio or something similar installed? Can you run RevitLookup and Revit.exe in the debugger and see where this happens? In that case, can you please wrap the offending line of code in a `try`/`catch` handler to handle the exception? And submit a pull request with the fixed code? That would be great! Thank you!

**Comment by jeremytammik** [comment]
I searched the RevitLookup source code globally to try to understand how this can occur. I searched, found and analysed all occurrences of `SnoopableObjectWrapper` and `GetUnderlyingType`, and they all make perfect sense and look perfectly all right to me. `GetTemplateParameterIds` is a member on the `View` class. It is called dynamically, and I cannot tell from your report how to trigger such a call. Therefore, it would be helpful if you could do so. The problem is probably trivial to fix and faster done than writing this long message. Looking forward to your pull request! Thank you!

**Comment by RevitArkitek** [comment]
When I debugged, Object in `public Type GetUnderlyingType() => Object.GetType();` was null.  I changed to `public Type GetUnderlyingType() => Object?.GetType();`  Then in the Objects.AddObjectsToTree I had to handle the null being returned.  After that, it would open the next dialog.

**Comment by jeremytammik** [comment]
Thank you! That helps narrow it down tremendously. Could you share the handling code in `AddObjectsToTree`, or submit a pull request for the changes? Have you made any other modifications and improvements? Cheers!

**Comment by RevitArkitek** [comment]
I'm going to do a little testing, and then try to do a Pull request.  I've never done that before.  Thanks!

**Comment by RevitArkitek** [comment]
I figured out that the main issue was further up the code and had to add a couple of handlers for these objects.  Unfortunately it won't let me push my commit.  Github desktop doesn't recognize my username/password.  Not sure how to proceed.

**Comment by jeremytammik** [comment]
Wow, that sounds very good! Looking forward very much to see your approach. Yes, that is completely normal. You cannot commit straight to my repository, since you might wreck the project for me. That is obvious and expected. The solution is easy: (i) fork my repository to your own copy of it. (ii) clone your repository, make changes, and commit as you please. (iii) in your forked directory, submit a pull request. that enables me to see the changes you made and merge them back into my main original source repo. it all makes total sense and is utterly powerful and convenient. you have learned something very valuable. search for something like [github fork commit pull merge](https://duckduckgo.com/?q=github+fork+commit+pull+merge). that gives many hits. one is [How to Fork Github Repository, Create Pull Request and Merge?](https://crunchify.com/how-to-fork-github-repository-create-pull-request-and-merge/).
